// <auto-generated />
namespace Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class corrida1cecilia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(corrida1cecilia));
        
        string IMigrationMetadata.Id
        {
            get { return "202111200001528_corrida-1-cecilia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
